[package]
name = "lago"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.23.0"
godot = {
  version = "0.5.4",
  features = ["api-4-7", "experimental-threads", "register-docs"]
}
image = "0.25.10"
itertools = "0.15.0"
krilla = "0.8.2"
krilla-svg = "0.8.1"
rayon = "1.12.0"
resvg = {
  version = "0.47.0",
  default-features = false,
  features = ["memmap-fonts", "text", "raster-images"]
}
zxing-cpp = { version = "0.5.3", features = ["bundled", "image"] }

[profile.dev]
opt-level = 1
debug = false

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
